name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - python-version: 2.7
              image: python:2.7-slim
            - python-version: 3.6
              image: python:3.6-slim
            - python-version: 3.7
              image: python:3.7-slim
    container:
      image: python:${{ matrix.python-version }}-slim
    steps:
      - uses: actions/checkout@v4
      - name: Check python version
        run: python --version
      - name: Install dependencies
        run: pip install --requirement requirements/testing.txt
      - name: Install PyDocX
        run: pip install -e .[dev]  # editable install so CLI entry points are available
      - name: Run tests
        run: nosetests --with-doctest
