name: CI

on:
  push:

jobs:
  superlegacy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [2.6, 3.3, 3.4]
        include:
          - python-version: 2.6
            image: cronosmobi/python2.6
          - python-version: 3.3
            image: python:3.3-slim
          - python-version: 3.4
            image: python:3.4-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests in Python ${{ matrix.python-version }}
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            python --version
            pip install --trusted-host pypi.org --index-url=http://pypi.org/simple "Jinja2==2.10" "MarkupSafe<2.0" "coverage==3.6" "nose==1.30" "flake8==2.6.2"
            pip install -e .
            nosetests --with-doctest

  legacy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python: [2.7, 3.6, 3.7, 3.8]
        include:
          - python: 2.7
            image: python:2.7-slim
          - python: 3.6
            image: python:3.6-slim
          - python: 3.7
            image: python:3.7-slim
          - python: 3.8
            image: python:3.8-slim

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4
      - name: Check python version
        run: python --version
      - name: Install dependencies
        run: pip install --requirement requirements/testing.txt
      - name: Install PyDocX
        run: pip install -e .[dev]  # editable install so CLI entry points are available
      - name: Run tests
        run: nosetests --with-doctest
